create table if not exists public.site_visits (
  id bigint generated by default as identity primary key,
  path text not null,
  referrer text not null default '',
  ip_address text not null default '',
  user_agent text not null default '',
  language text not null default '',
  screen text not null default '',
  viewport text not null default '',
  page_title text not null default '',
  country text not null default '',
  timezone_offset integer,
  created_at timestamptz not null default now()
);

create index if not exists site_visits_created_at_idx
  on public.site_visits (created_at desc);

create index if not exists site_visits_path_idx
  on public.site_visits (path);
