const pricingSeedServices = [
  {
    serviceKey: 'websites',
    label: 'Websites',
    icon: 'code',
    intro: 'Responsive websites, business platforms, content systems, and online stores built around your goals.',
    displayOrder: 1,
    active: true,
    packages: [
      {
        tier: 'Basic',
        title: 'Basic Website',
        price: 'Rs. 45,000',
        description: 'Suitable for individuals, portfolios and small businesses.',
        delivery: '7-10 working days',
        button: 'Choose Basic',
        displayOrder: 1,
        active: true,
        features: [
          'Up to 5 pages',
          'Modern responsive design',
          'Mobile, tablet and desktop support',
          'Contact form',
          'WhatsApp and social media links',
          'Google Maps integration',
          'Basic search engine optimization',
          'Basic performance optimization',
          'One revision round',
          '30 days of technical support',
        ],
        unavailable: [
          'Content management system',
          'Admin dashboard',
          'Blog or news section',
          'E-commerce or booking system',
          'Online payment integration',
          'User registration and login',
        ],
      },
      {
        tier: 'Standard',
        title: 'Standard Website',
        price: 'Rs. 85,000',
        description: 'Suitable for growing businesses that need to manage their website content.',
        delivery: '2-3 weeks',
        badge: 'Most Popular',
        button: 'Choose Standard',
        displayOrder: 2,
        active: true,
        features: [
          'Up to 10 pages',
          'Custom UI/UX design',
          'Content management system',
          'Admin dashboard',
          'Blog or news section',
          'Contact and inquiry management',
          'WhatsApp integration',
          'Google Analytics integration',
          'Advanced search engine optimization',
          'Speed and security optimization',
          'Three revision rounds',
          '60 days of technical support',
        ],
        unavailable: [
          'E-commerce, booking or reservation system',
          'Online payment integration',
          'User registration and login',
          'Advanced API integrations',
          'Advanced analytics and reporting',
        ],
      },
      {
        tier: 'Premium',
        title: 'Premium Website',
        price: 'Rs. 150,000',
        description: 'Suitable for advanced business websites, online stores and custom platforms.',
        delivery: '4-6 weeks',
        button: 'Choose Premium',
        displayOrder: 3,
        active: true,
        features: [
          'Unlimited essential pages',
          'Fully customized UI/UX design',
          'Advanced admin dashboard',
          'E-commerce, booking or reservation system',
          'Online payment integration',
          'User registration and login',
          'Email notification system',
          'Third-party API integrations',
          'Advanced security and performance optimization',
          'Analytics and reporting',
          'Deployment assistance',
          'Five revision rounds',
          '90 days of technical support',
        ],
        unavailable: [
          'Domain, hosting and third-party service fees',
          'Ongoing monthly maintenance after support period',
          'Paid plugin, payment gateway or email provider charges',
        ],
      },
    ],
  },
  {
    serviceKey: 'mobile-apps',
    label: 'Mobile Apps',
    icon: 'phone',
    intro: 'Android and iOS applications shaped for MVP launches, business workflows, and scalable products.',
    displayOrder: 2,
    active: true,
    packages: [
      {
        tier: 'Basic',
        title: 'Basic Mobile App',
        price: 'Rs. 120,000',
        description: 'Suitable for simple business apps and minimum viable products.',
        delivery: '3-4 weeks',
        button: 'Choose Basic',
        displayOrder: 1,
        active: true,
        features: [
          'Android or iOS application',
          'Up to 5 main screens',
          'Responsive mobile interface',
          'Basic user login',
          'Simple database integration',
          'Basic API integration',
          'Contact or inquiry features',
          'Basic testing',
          'Application build file',
          'One revision round',
          '30 days of technical support',
        ],
        unavailable: [
          'Android and iOS together',
          'Custom backend development',
          'Admin dashboard',
          'Push notifications',
          'App Store and Play Store submission assistance',
          'Payment, maps, chat or real-time features',
        ],
      },
      {
        tier: 'Standard',
        title: 'Standard Mobile App',
        price: 'Rs. 250,000',
        description: 'Suitable for businesses that need a complete application for Android and iOS.',
        delivery: '6-8 weeks',
        badge: 'Most Popular',
        button: 'Choose Standard',
        displayOrder: 2,
        active: true,
        features: [
          'Android and iOS applications',
          'Up to 12 main screens',
          'Custom UI/UX design',
          'User registration and login',
          'Database and backend development',
          'Admin dashboard',
          'Push notifications',
          'API integrations',
          'User profile management',
          'Basic analytics',
          'App Store and Play Store submission assistance',
          'Three revision rounds',
          '60 days of technical support',
        ],
        unavailable: [
          'Payment gateway integration',
          'Google Maps and location tracking',
          'Real-time chat or messaging features',
          'Role-based user accounts',
          'Advanced analytics and reporting',
        ],
      },
      {
        tier: 'Premium',
        title: 'Premium Mobile App',
        price: 'Rs. 450,000',
        description: 'Suitable for startups and businesses that require a scalable custom application.',
        delivery: '10-16 weeks',
        button: 'Choose Premium',
        displayOrder: 3,
        active: true,
        features: [
          'Android and iOS applications',
          'Fully customized UI/UX',
          'Advanced backend system',
          'Advanced admin dashboard',
          'Payment gateway integration',
          'Google Maps and location tracking',
          'Real-time notifications',
          'Chat or messaging features',
          'Role-based user accounts',
          'Advanced API integrations',
          'Analytics and reporting',
          'Security and performance optimization',
          'Store deployment assistance',
          'Five revision rounds',
          '90 days of technical support',
        ],
        unavailable: [
          'App store, developer account and third-party service fees',
          'Ongoing monthly maintenance after support period',
          'Paid SMS, email, maps or payment provider charges',
        ],
      },
    ],
  },
];

module.exports = { pricingSeedServices };
